language: python
python:
- 3.6
notifications:
  email: false
  webhooks: https://coveralls.io/webhooks
env:
  global:
  - COVERALLS_PARALLEL=true
  matrix:
  - TESTFILES="tests/test_expected_factor_analyzer.py"
  - TESTFILES="tests/test_expected_rotator.py"
  - TESTFILES="tests/test_factor_analyzer.py"
sudo: false
before_install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b -f
- ${HOME}/miniconda3/bin/conda update --yes conda

install:
- ${HOME}/miniconda3/bin/conda install --file conda_requirements.txt --yes
- ${HOME}/miniconda3/bin/pip install nose-cov python-coveralls
- ${HOME}/miniconda3/bin/pip install -e .

script:
- ${HOME}/miniconda3/bin/nosetests -v tests --with-coverage --cover-package=factor_analyzer --cov-config .coveragerc

after_success:
- ${HOME}/miniconda3/bin/coveralls -c .coveragerc
