
version: 2
jobs:

  build:
    environment:
       COVERALLS_REPO_TOKEN: aSN6kpjINvc8uDM9OxnRW0bPcbBbhFLz5
    docker:
      - image: buildpack-deps:trusty
    working_directory: ~/factor_analyzer
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "conda_requirements.txt" }}
          - v1-dependencies-

      - run:
          name: Install miniconda and dependencies
          command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            chmod +x miniconda.sh
            ./miniconda.sh -b -f
            ~/miniconda3/bin/conda install --file conda_requirements.txt --yes
            ~/miniconda3/bin/pip install nose-cov python-coveralls

      - save_cache:
          paths:
            - ~/factor_analyzer
          key: v1-dependencies-{{ checksum "conda_requirements.txt" }}

      # install factor analyzer
      - run:
          name: Install factor analyzer
          command: ~/miniconda3/bin/pip install -e .

      # run all of the tests
      - run:
          name: Run tests
          command: ~/miniconda3/bin/nosetests -v tests --with-coverage --cover-package=factor_analyzer --cov-config .coveragerc

      # change to factor analyzer directory and run coveralls
      - run:
          name: Run coveralls
          command: cd ~/factor_analyzer && ~/miniconda3/bin/coveralls

# custom notification for coveralls
notify:
  webhooks:
      - url: https://coveralls.io/webhook?repo_token=aSN6kpjINvc8uDM9OxnRW0bPcbBbhFLz5
